services:
  mariadb-server:
    container_name: mariadb-server
    image: mariadb:11.4.5
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./mariadb_data:/var/lib/mysql
      - /home/classbox/Desktop/106-exercises/:/workspace

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: mariadb-server
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8080:80"
    depends_on:
      - mariadb-server

  sql-injection:
    container_name: sql-injection
    build: ./sql-injection/
    restart: always
    volumes:
      - ./sql-injection:/usr/app/
      - /usr/app/node_modules
    ports:
      - "8081:8081"
    depends_on:
      - mariadb-server
    environment:
      DB_HOST: mariadb-server
      DB_USER: root
      DB_PASS: root
    command: npm run dev
